### ISSUE TITLE
Selecting terms and then changing the application window causes issues with text editing

### ISSUE THREAD

**Issue by SohailKh** [tedwards8/Xcode-Multi-Edit#1]
Steps to reproduce:
1. Select a series of terms using option+shift+d
2. Do not unselect
3. Click elsewhere and try to edit.

Clicking somewhere else should deselect the currently selected terms.

**Comment by timwredwards** [comment]
Possible by listening to NSTextViewDidChangeSelectionNotification. Will take a look.

**Comment by timwredwards** [comment]
@SohailKh Is this now resolved?

**Comment by SohailKh** [comment]
yep, thanks!
