### ISSUE TITLE
When I press "Shift-Option-A", output Å

### ISSUE THREAD

**Issue by wonderffee** [tedwards8/Xcode-Multi-Edit#6]
I still have no idea how to use the shortcut, is there some special setting?

**Comment by wonderffee** [comment]
sorry, need restart xcode.

**Comment by tjdaniel2** [comment]
I'm having this same issue. I am running Version 7.2 (7C68). I have tried restarting Xcode and removing and reinstalling the plugin but with no luck.

**Comment by wonderffee** [comment]
@tjdaniel2  Maybe you need this: https://github.com/ForkPanda/RescueXcodePlug-ins

**Comment by timwredwards** [comment]
If not, please try cloning this repo and running the project in Xcode. You should get some error output that can help me rectify the issue.

**Comment by tjdaniel2** [comment]
I'm sorry I don't look at my github account much since I left college but i just saw you posted a replay. Running the script from your suggestion worked. Thanks. It is so nice having that functionality in Xcode.
